# Generated by Django 4.0.5 on 2023-05-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft_Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material_composition', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('condition', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('aircraft_model', models.CharField(max_length=255)),
                ('potential_use_cases', models.TextField()),
                ('new_parts_carbon_footprint', models.FloatField(blank=True, null=True)),
                ('recycled_parts_carbon_footprint', models.FloatField(blank=True, null=True)),
                ('water_usage_new_parts', models.FloatField(blank=True, null=True)),
                ('water_usage_recycled_parts', models.FloatField(blank=True, null=True)),
                ('landfill_waste_new_parts', models.FloatField(blank=True, null=True)),
                ('landfill_waste_recycled_parts', models.FloatField(blank=True, null=True)),
                ('energy_consumption_new_parts', models.FloatField(blank=True, null=True)),
                ('energy_consumption_recycled_parts', models.FloatField(blank=True, null=True)),
                ('recycling_rate', models.FloatField(blank=True, null=True)),
                ('toxicity_score_new_parts', models.FloatField(blank=True, null=True)),
                ('toxicity_score_recycled_parts', models.FloatField(blank=True, null=True)),
                ('remanufacturing_potential', models.CharField(max_length=255)),
                ('life_cycle_assessment', models.CharField(max_length=255)),
                ('renewable_material_content', models.FloatField(blank=True, null=True)),
                ('carbon_footprint_saved', models.FloatField(blank=True, null=True)),
                ('water_usage_saved', models.FloatField(blank=True, null=True)),
                ('landfill_waste_saved', models.FloatField(blank=True, null=True)),
                ('energy_consumption_saved', models.FloatField(blank=True, null=True)),
                ('toxicity_score_difference', models.FloatField(blank=True, null=True)),
                ('remanufacturing_potential_percent', models.FloatField(blank=True, null=True)),
                ('life_cycle_assessment_score', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
