# Generated by Django 4.0.5 on 2023-05-12 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aircrafts', '0002_aircraft_part_status_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft_part',
            name='added_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
